name: sznm_dart_packages
repository: https://github.com/sozonome/sznm_dart_packages

packages:
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: dart analyze .

sdkPath: .fvm/flutter_sdk